### ISSUE TITLE
display

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#10]
Under sermons show hits is on and when you load page this shows for second, but then disappears  example http://www.audiosermon.net/sermons/preacher/keith-daniel

**Comment by Llewellynvdm** [comment]
I can not see what you are seeing, to me it seems to work as expected. Maybe you should explain little more.

**Comment by roybinhood** [comment]
I turned off cache so you would not see it

On Tue, Mar 8, 2016 at 9:09 PM, Llewellyn <notifications@github.com> wrote:

> I can not see what you are seeing, to me it seems to work as expected.
> Maybe you should explain little more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SermonDistributor/Joomla-3-Component/issues/10#issuecomment-193920934>
> .
>



-- 
Thank you so much
Roy and Jerusala Daniel
