### ISSUE TITLE
Possible bug cache

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#12]
I don't know if this is a bug or not but when I turn conservative cache on all the option settings go random, for instance on http://www.audiosermon.net/sermons when I turn conservative cache on the front end some preachers go to pages set up one way and others do something totally different. Then when I turn cache on all is fine again ? This is not just a wait for cache to update problem as it is in all 3 browsers the same.

**Comment by Llewellynvdm** [comment]
I do think you need to  clear your browser cache if you make any changes. Please not that our own website that use Sermon Distributor called[ loudvoice](http://www.loudvoice.org/) has progressive caching on and works well.

**Comment by roybinhood** [comment]
On my joomla website just by turning on cache it messes it up. Then if I use 3 different browsers with cleared cache it is the same on all with no changes made before. I suppose it is just my site :-(

**Comment by roybinhood** [comment]
It seams to have been resolved
