### ISSUE TITLE
H1 Header Structure

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#14]
In looking at page structures of major audio sermon sites the list of speakers is H3 header titles like yours, but when you open a individual preacher or single sermon the preacher title ( for his section) and the single sermon title indivual pages have the preacher and title as H1 headers respectively ? This is not an option and would be nice for google to know name of preacher in a single preacher section is important for that page or title of sermon if on a single sermon page example 

1) On this page the speakers should be H1 (although a page title H1 header would be a nice option)

2) On this single speaker page the speakers name should be H1 http://www.audiosermon.net/sermons/preacher/allen-redpath

3) On this single sermon page the sermon title should be an H1 header 
http://www.audiosermon.net/sermons/sermon/a-day-of-fierce-conflict-allen-redpath

Here is an example page on sermonindex.net where the speaker name is H1 Header

http://www.sermonindex.net/modules/mydownloads/viewcat.php?cid=1

**Comment by Llewellynvdm** [comment]
Sure we can look at that, I mean to add the option for you to choose the header type per view.
