### ISSUE TITLE
JPlayer not viewing/working properly 

### ISSUE THREAD

**Issue by zydulum** [SermonDistributor/Joomla-3-Component#23]
Player will play file, buttons are not viewing right and the slider doesn't work.
<a href="https://gyazo.com/e961acdef12130ebde2a0706c67d7f5f"><img src="https://i.gyazo.com/e961acdef12130ebde2a0706c67d7f5f.gif" alt="https://gyazo.com/e961acdef12130ebde2a0706c67d7f5f" width="456"/></a>

**Comment by roybinhood** [comment]
Dear Zydulum can you give example page on your site ?

**Comment by zydulum** [comment]
http://amesburybaptist.org.uk/sermons/sermon/example

**Comment by Llewellynvdm** [comment]
Hi Zydulum

There is another css style on the page that conflict with the jplayer styles, just to mention on group style from the s5 template:
~~~css
.jdGallery .carousel .carouselInner .active, .readon:hover, .s5_ts_active a, .icon_outer_wrap:hover, .icon_hover, #s5_register:hover, #s5_login:hover, #s5_ls_outer_wrap .s5_ls_readmore:hover, button:hover, .button:hover, .pagenav a:hover, p.readmore a:hover, span.s5_pagespan a:hover, .module_round_box-highlight2 
{
    background: #2aa26d none repeat scroll 0 0 !important;
}
~~~
To resolve this may require good knowledge on CSS styles, and posibly edit the template CSS or the player CSS.

For you to test if this is really the case, load the default Joomla template on that page and see if the player is still acting weird.

So this does not look like a bug, but only conflicting CSS styles.

**Comment by zydulum** [comment]
have tried default theme and has fix the buttons, but being able to skip ahead on the playerbar is still not working

**Comment by Llewellynvdm** [comment]
Hmmm okay, lets see that skin comes from [jPlayer repo](https://github.com/happyworm/jPlayer), here is a link to their [demos](http://www.jplayer.org/latest/demos/) so you could look around their forums and see if you find any hint to why this is happening.

The other test I would ask you to make is change the file download option to direct and lets see if the player still gives issues. We found that the download encryption is not working flawless. I am working on it but it will still be some time before the fix is ready.

So if you could on that example file use direct and lets see if it works.

**Comment by roybinhood** [comment]
"Seek bar" I also have Seek bar that does not work and I am using uikit and yootheme ...

Here is example of seek bar not working 

http://www.audiosermon.net/a/sermon/are-you-a-vital-christian-allen-redpath

**Comment by roybinhood** [comment]
Out of interest Lewellyn I found a site using jplayer with a very nice skin, but cant find name or source of skin ... Here is an example of player with skin though  ... source code shows it is jplayer http://www.mixest.com/0wb

**Comment by roybinhood** [comment]
Okay I have news Did you know the SEEK BAR works ... wait for this in ... the browser "Internet Explorer" , but not in  firefox and I suppose Chrome :-) That is interesting ?

**Comment by roybinhood** [comment]
I updated to latest version of firefox and it works even more shakily sometimes taking a few clicks to start... but in Internet Explorer it works fine ??? Interesting

**Comment by zydulum** [comment]
changed the file download option to direct, can everything is working fine now

**Comment by Llewellynvdm** [comment]
I am still working on the fix (so there is a fix coming for this issue), but thanks for letting me know.
