### ISSUE TITLE
Dropbox integration broke

### ISSUE THREAD

**Issue by Llewellynvdm** [SermonDistributor/Joomla-3-Component#25]
We need to urgently move over to a new way of integrating Dropbox, the old way has completely broken down. 

This is because Dropbox has made major changes to their website and so forcing all to make use of their API instead.

**Comment by roybinhood** [comment]
Will pray for you for wisdom in this regard ...

**Comment by Llewellynvdm** [comment]
### The upgrade is almost ready!

There are a few changes, mainly that you will need a Dropbox app now to load the shared url's. We will make a new tutorial once the update is released to demonstrate this new method. Secondly we will be adding two new tables ***external_source*** and ***local_listing*** 

All the previous Dropbox settings will be moved to the ***external_source*** table and you will need to make all the needed changes manually after reviewing the new tutorial. Since you will need a token from Dropbox to update the new local listing. 

### Important Notice

All previous linked sermons, that are linked to Dropbox will continue to work once you have made the needed changes and ran the update. We have made all the needed adaptations to insure that once you have updated your Dropbox listings the linking method will work just as before. This will mean that if no changes were made to your Dropbox, the files will just link and work as before. We will in the new tutorial demonstrate this concept in more depth.

**Comment by roybinhood** [comment]
Dear Sir I am so excited !!!
