### ISSUE TITLE
Html 5 player

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#28]
I have checked on loudvoice on a laptop and desktop on multiple browsers and basically the html5 player when you choose a point on time line it does not go to that point , but either carries on playing at same point or fills up the timeeline bar in a few seconds and then plays on till end.... ie you cannot choose where in sermon specifically to play at ... It does not work... ? It seems to work when you hover, but not when you click on timeline. Example here http://www.loudvoice.org/a/sermon/a-pastors-telling-of-the-life-of-aw-tozer

**Comment by Llewellynvdm** [comment]
Please watch this video where I show the test of the HTML5 player https://youtu.be/m3SXruMoKqc

**Comment by roybinhood** [comment]
Dear Lewellyn , Your youtube video works with short hymns , but not with long sermons ( like link I gave you) on many many devices. I am not trying to to find problems, we just genuinely have a problem on many devices here. The file only downloads one third of the bar with long sermons and gives many problems trying to click on a specific point on time line of sermon which is totally different to a small hymn file working. Sorry t open this again but still problem on multiple browsers , devices and on your and our sites.
