### ISSUE TITLE
New Sermon Highlight

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#3]
Is it possible that new sermons have a little red "new" above title so people can see sermons loaded recently. This is on audiosermon.net and is nice.

**Comment by Llewellynvdm** [comment]
Well the amount of hits should give away that a sermon is new. But sure we can take a look at this feature, I will keep you posted.

**Comment by roybinhood** [comment]
Thanks it is something that sermonaudio.com does and people like it .
