### ISSUE TITLE
New documentation for DropBox support ?

### ISSUE THREAD

**Issue by webiedesign** [SermonDistributor/Joomla-3-Component#32]
The video I watched says "watch the new video for Dropbox" - where is the new video ? I am having trouble getting Dropbox files to play.

**Comment by Llewellynvdm** [comment]
Hi, I have not yet made the new video... the process is sort of the same, just that you can now have more then one, and it has its own area in SD.

I have placed a lost of help in the descriptions of the fields, with some notes all around the area. But you are right I should make a new tutorial... just do not have time right now... will keep you posted.

**Comment by webiedesign** [comment]
I was able to resolve my issue. I used https://www.opendrive.com/ and called the files via the url option and their "streaming" link. Works perfect for us, thank you
