### ISSUE TITLE
Bible

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#9]
Can sermons be not only linked to specific verse in bible but when you open your bible software in joomla can the verses with sermons related to them have an open shown clearly to send people to sermons on that topic on same site ? So as people search through Bible they can find sermons linked to verses they searched for or read ?

**Comment by Llewellynvdm** [comment]
Please list this as a feature request with [getBible](https://github.com/getbible/Joomla-3-Component/issues), since this will need to be implemented on their side.

**Comment by roybinhood** [comment]
Okay !
